apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging
resources:
  - ../../base

# Le CD fixe les images réelles :
#   kustomize edit set image trustpass-backend=<acr>/trustpass-backend:<tag>
#                            trustpass-frontend=<acr>/trustpass-frontend:<tag>

patches:
  - target:
      kind: ConfigMap
      name: trustpass-config
    patch: |-
      - op: replace
        path: /data/CORS_ORIGIN
        value: "http://staging.trustpass.local"
  - target:
      kind: Ingress
      name: trustpass
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: "staging.trustpass.local"
