apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: preprod
resources:
  - ../../base

patches:
  - target:
      kind: ConfigMap
      name: trustpass-config
    patch: |-
      - op: replace
        path: /data/CORS_ORIGIN
        value: "http://preprod.trustpass.local"
  - target:
      kind: Ingress
      name: trustpass
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: "preprod.trustpass.local"
